markdownSlides:
#  image: busybox:latest
  stage: deploy
  script:
    - echo "copy images..."
    - cp slides/*.png slides/*.jpg slides/*.webp slides/*.svg /var/www/courses.fmsoft.cn/aple/assets -f
    - echo "copy HTML files..."
    - cp slides/*.html /var/www/courses.fmsoft.cn/aple/ -f
    - echo "copy markdown files..."
    - cp slides/*.md /var/www/courses.fmsoft.cn/aple/gitlab/ -f
    - echo "done"
  only:
    refs:
      - master
    changes:
      - slides/*

